### Encoding : categorical data -------------> Numerical data

Nominal / One Hot Encoding(OHE)

in this each category is represented as a Binary Vector Where each bit corresponds to a unique Category

In [1]:
import pandas as pd
df = pd.DataFrame({
    'color' : ['red', 'blue', 'green', 'red', 'blue']
})

In [ ]:
### Creating and instance of ohe
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [3]:
# perform fit and transform

encoded = encoder.fit_transform(df[['color']]).toarray()

In [4]:
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out(['color']))

In [5]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [6]:
import seaborn as sns

df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['day']]).toarray()
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out(['day']))

encoded_df

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [8]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']